bind 0.0.0.0
protected-mode yes
port 6379
save ""
appendonly no
maxmemory 512mb
maxmemory-policy noeviction
dir /data
loglevel warning
aclfile /run/secrets/users.acl
acllog-max-len 0
slowlog-log-slower-than -1
latency-monitor-threshold 0
